### PR TITLE
OvmfPkg/QemuVideoDxe: add feature PCD to remap framebuffer W/C

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
============ RFC =============
QEMU no longer permits misaligned access to device memory, which breaks QemuVideoDxe on SbsaQemu.

This is one potential work-around - it is quick and dirty hack, and I'm open to alternative approaches.

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
@hrw

**Comment by bcran** [comment]
I had a discussion with @hrw on Twitter and he linked me to https://lore.kernel.org/qemu-devel/20240301204110.656742-1-richard.henderson@linaro.org/ which is where the change happened.

I haven't had a chance to understand the change: is this a bug in Qemu? Or is it just more correctly emulating AArch64?

**Comment by ardbiesheuvel** [comment]
> I had a discussion with @hrw on Twitter and he linked me to https://lore.kernel.org/qemu-devel/20240301204110.656742-1-richard.henderson@linaro.org/ which is where the change in Qemu behavior happened.
> 
> I haven't had a chance to understand the change: is this a bug in Qemu? Or is it just more correctly emulating AArch64?

The latter.

QemuVideoDxe was already broken in the same way when running under KVM, but it was never a problem because there are other reasons (related to memory coherency) that prevent us from using that driver on ArmVirtQemu, so it was removed from the primary ARM-related virtual platforms.

SbsaQemu is intentionally more geared towards emulation of a system topology that resembles what you might encounter on an actual bare metal platform, and so VGA PCIe controllers are supported too, by means of the QemuVideoDxe driver, which ignores memory attributes for framebuffers entirely.

**Comment by leiflindholm** [comment]
I'm happy with this change. I guess on x86 this ends up architecturally as a no-op?

**Comment by kraxel** [comment]
> I'm happy with this change. I guess on x86 this ends up architecturally as a no-op?

Nope.  x86 tries (and fails) to setup MTRR registers.  Which is I guess  the reason why @ardbiesheuvel has added PCD to enable this behaviour.

**Comment by kraxel** [comment]
I'd suggest to apply the attribute to the complete pci bar, i.e. use `FrameBufDesc->AddrRangeMin` + `FrameBufDesc->AddrLen`.  Otherwise looks good to me.

**Review by kraxel — APPROVED** [review]

**Review by leiflindholm — APPROVED** [review]

**Comment by bcran** [comment]
I removed the 'push' label because someone added a merge commit instead of rebasing the branch.

**Review by bcran — APPROVED** [review]

**Comment by ardbiesheuvel** [comment]
> @ardbiesheuvel Could you remove the merge commit please?
> 
> > [Merge branch 'master' into rfc-qemu-pci-framebuffer-remap-wc](https://github.com/tianocore/edk2/pull/5786/commits/2fe3f4b7f06d1c8d959374f532e06cc5efee416c)

Mergify creates these automatically, but somehow, they don't end up on the main branch.

**Comment by bcran** [comment]
> > @ardbiesheuvel Could you remove the merge commit please?
> > > [Merge branch 'master' into rfc-qemu-pci-framebuffer-remap-wc](https://github.com/tianocore/edk2/pull/5786/commits/2fe3f4b7f06d1c8d959374f532e06cc5efee416c)
> 
> Mergify creates these automatically, but somehow, they don't end up on the main branch. You can just ignore them.

Oh I didn't realize - sorry for canceling the push!

**Comment by ardbiesheuvel** [comment]
> > > @ardbiesheuvel Could you remove the merge commit please?
> > > > [Merge branch 'master' into rfc-qemu-pci-framebuffer-remap-wc](https://github.com/tianocore/edk2/pull/5786/commits/2fe3f4b7f06d1c8d959374f532e06cc5efee416c)
> > 
> > 
> > Mergify creates these automatically, but somehow, they don't end up on the main branch. You can just ignore them.
> 
> Oh I didn't realize - sorry for canceling the push!

No worries

**Pull request merged**
