### PR TITLE
Pr example missing uncrustify attachments

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
DO NOT MERGE

Example PR to illustrate missing attachments in uncrustify failure reports.

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
@makubacki

**Comment by makubacki** [comment]
I see the Uncrustify error attachment in the pipelines currently run for this PR for `ArmVirtPkg` but not `ArmPkg`. 
https://dev.azure.com/tianocore/edk2-ci/_build/results?buildId=138714&view=ms.vss-test-web.build-test-results-tab&runId=1261243&resultId=100010&paneView=debug

image

`ArmPkg` has Uncrustify in AuditOnly mode whereas `ArmVirtPkg` does not.

- [ArmVirtPkg.ci.yaml](https://github.com/tianocore/edk2/blob/master/ArmVirtPkg/ArmVirtPkg.ci.yaml)
- [ArmPkg.ci.yaml](https://github.com/tianocore/edk2/blob/master/ArmPkg/ArmPkg.ci.yaml#L244-L247)

This led to the Uncrustify result being a failure in the `ArmVirtPkg` CI log:

```
INFO - Calculating file diffs. This might take a while...
INFO - Formatting errors in Library\ArmVirtQemuMonitorPeiLib\ArmVirtQemuMonitorPeiLib.c
ERROR - --->Test Failed: Uncrustify Coding Standard Test NO-TARGET returned 1
```

And the Uncrustify result being a non-failure in the `ArmPkg` CI log:

```
INFO - Formatting errors in Library\ArmMonitorLib\ArmMonitorLib.c
INFO - Formatting errors in Library\DebugPeCoffExtraActionLib\DebugPeCoffExtraActionLib.c
INFO - Setting test as skipped since AuditOnly is enabled
WARNING - --->Test Skipped: in plugin! Uncrustify Coding Standard Test NO-TARGET
```

Is the result you expected? Based the previous discussion, I thought the issue would be the attachment would not be present in the UI for `ArmVirtPkg`.

**Comment by ardbiesheuvel** [comment]
Thanks for taking a look.

> 
> Is the result you expected? Based the previous discussion, I thought the issue would be the attachment would not be present in the UI for `ArmVirtPkg`.

That was indeed the issue. And bizarrely, when I created this PR, all the test results were immediately populated with the data taken from the prior test run - the same commit ID was already used on the other PR, which is also what mergify warns about.

I double checked and did not see the attachments when I looked at the cached test results right after creating the PR. But now they are there.

Not sure what is going on here, but the current situation is acceptable to me - it takes a bit of digging but at least the CI can tell me itself why it rejected a PR.

**Comment by makubacki** [comment]
> Thanks for taking a look.
> 
> > Is the result you expected? Based the previous discussion, I thought the issue would be the attachment would not be present in the UI for `ArmVirtPkg`.
> 
> That was indeed the issue. And bizarrely, when I created this PR, all the test results were immediately populated with the data taken from the prior test run - the same commit ID was already used on the other PR, which is also what mergify warns about.
> 
> I double checked and did not see the attachments when I looked at the cached test results right after creating the PR. But now they are there.
> 
> Not sure what is going on here, but the current situation is acceptable to me - it takes a bit of digging but at least the CI can tell me itself why it rejected a PR.

I checked the XML in both cases and I didn't see a difference in the way the Uncrustify results were reported. Let me know if you continue to see it happen and we can try to find someone to take a deeper look.

**Pull request closed without merging**
