### PR TITLE
[BZ-4860] FatPkg/FatPei: Simplify the GPT Header Check

### PR DESCRIPTION
**Pull request by linjaso1**
# Description

- [Bugzilla#4860](https://bugzilla.tianocore.org/show_bug.cgi?id=4860)

- The condition of GPT header checking is mismatched between PEI ```FatPei``` module in ```FatPkg``` and DXE ```PartitionDxe``` module in ```MdeModulePkg```.

- This patch is intended to simplify the checking condition within ```FatPei``` module to align with ```PartitionDxe``` module to reduce code flow gap between both of them.

- Below of condition would be checked on GPT header aligned with DXE ```PartitionDxe``` module,
  1. GPT header signature value
  2. GPT header CRC value
  3. GPT header LBA value
  4. GPT header size of partition entry

- [ ] Breaking change?
  - No, it is removed the redundant condition to check the GPT header within the module only.

- [ ] Impacts security?
  - No, this change do not include any security-related change.

- [X] Includes tests?
  - Yes, check the FatPkg self-build is passing without any issue.

## How This Was Tested

- Check the GPT partition header could be checked successfully without any issue on ```FatPei``` module in PEI phase

- Tested on both of ```Windows``` and ```Ubuntu``` OS

## Integration Instructions

- N/A.

### CODE REVIEW

**Review by niruiyu — COMMENTED** [review]
What issue is there with the current GPT Header Check logic in the FatPei?
I cannot find the details in the commit message or bugzilla.

**Comment by linjaso1** [comment]
Hi @niruiyu ,

Updated in the Bugzilla for the cases.

**Review by niruiyu — APPROVED** [review]

**Comment by lgao4** [comment]
@linjaso1 , @niruiyu , this is a bug fix. Do you think it is a crital issue that is requried to be merged into the stable tag 202411?

**Comment by linjaso1** [comment]
Hi @lgao4 ,

As a author, it would be better if we could include this change in stable tag if we could.

**Comment by lgao4** [comment]
> Hi @lgao4 ,
> 
> As a author, it would be better if we could include this change in stable tag.

@niruiyu , @mdkinney , what's your opinion？

**Review by mdkinney — APPROVED** [review]

**Comment by mdkinney** [comment]
Approve for edk2-stable202411

**Pull request merged**
