### PR TITLE
MdePkg: 

### PR DESCRIPTION
**Pull request by vit9696**
MdePkg: Introduce assertion on constraint debug mask bit

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2054

This bit allows to control assertion on constrain violation.

Signed-off-by: Vitaly Cheptsov <vit9696@protonmail.com>

### CODE REVIEW

**Comment by corthon** [comment]
Why was it decided to split the library rather than just remove the ASSERTs from SafeString? I feel like I might have voted for removal, but can't find the conversation.

**Comment by vit9696** [comment]
Intel guys fight with preserving it very badly. Basically their primary reason is that their environment is trusted and having these assertions triggered means something went wrong. It makes little sense, but you can follow it yourself if you want[1]. Basically we have been fighting for over a year already.

[1] https://edk2.groups.io/g/devel/search?ev=false&q=constraint+assertions

**Comment by corthon** [comment]
Yeah, I figured there must be history here. Still looking at your changes. Seems fine, if this is the final architecture.

Thanks for putting it in a PR as well! Much easier to review.

**Comment by corthon** [comment]
Yeah, looking at it, it feels like it would be the responsibility of the *caller* to decide that they want to ASSERT based on what the input is and the likelihood that it would violate a constraint.

But I'm not going to rehash long-settled design choices at the 11th hour. Your changes look good for me.

**Comment by vit9696** [comment]
Thx, feel free to review this on the mailing list.

**Pull request closed without merging**
