### PR TITLE
riscv: Add RISC-V support.

### PR DESCRIPTION
**Pull request by kallisti5**
* This is based on rebased work from HP 2017 they seemingly abandoned
  here: https://github.com/HewlettPackard/RiscVEdk2
* Copyrights maintained to ensure compliance.

### CODE REVIEW

**Comment by kallisti5** [comment]
This is untested, likely majorly broken still.  Submitting for feedback while I work on it :-)

**Comment by kallisti5** [comment]
I've been asking around, and this work might be duplicated.

```
17:20 < davidlt> kallisti5, hi                                                                                                                                                                 |
17:20 < davidlt> kallisti5, Tianocore EDK2 already boots on Unleashed                                                                                                                          |
17:21 < davidlt> kallisti5, it's being merged (it was even mentioned on a talk at FOSDEM), the target is 2020 Q2                                                                               |
17:21 < davidlt> So nothing is abandoned, but the current code lives in a different place, I think                                                                                             |
17:22 < davidlt> kallisti5, I don't follow it precisely, but riscv stuff should be in tianocore edk2 staging repository                                                                        |
17:24 < davidlt> today I actually saw UEFI boot of kernel on riscv64                                                                                                                           |
17:25 < davidlt> EBBR seems to be really close, but things need to polished/finalized/reviewed                                                                                                 |
```


```
22:30 < futarisIRCcloud> kallisti5: rminnich says: it was vaporware. no other reason
22:51 < futarisIRCcloud> Neutral source? Phillip Hug (philhug?) said tianocore should be ready in Q2.                                                                                          |
```

I'm putting the brakes on my work here until some more details come to light about the above.. I really don't want to duplicate effort in-case someone else has some yet-to-be-upstreamed UEFI work. (though, a lot of this stuff could have been merged already without being complete.  Keeping code "completely out of tree until done" is a bit annoying.

**Comment by JohnAZoidberg** [comment]
We (HPE) are still actively working on it.
Here: https://github.com/tianocore/edk2-staging/commits/RISC-V-V2

Have you made additional changes? Do you have suggestions? Please follow the mailing list :)

**Comment by JohnAZoidberg** [comment]
We're tracking the progress here: https://github.com/riscv/riscv-uefi-edk2-docs

**Comment by lersek** [comment]
edk2 CI has been enabled for RISC-V recently, under https://bugzilla.tianocore.org/show_bug.cgi?id=2562. RISC-V package additions to edk2 are tracked under https://bugzilla.tianocore.org/show_bug.cgi?id=2532. Closing this PR.

**Comment by kallisti5** [comment]
Small note on this one (posting here to cc everyone who has touched it who has RISCV64 interests)
Haiku now produces RISCV64 builds which have a RISCV64 EFI bootloader included.

Might be a good candidate to play with.

https://download.haiku-os.org/nightly-images/riscv64/

**Pull request closed without merging**
