### PR TITLE
MdeModulePkg/SmiHandlerProfileInfo: Include profile in profile

### PR DESCRIPTION
**Pull request by makubacki**
# Description

Includes the profiler SMI in the profile itself for completeness.

- [ ] Breaking change?
- [ ] Impacts security?
- [ ] Includes tests?

## How This Was Tested

- Review SMI profile output to see the profiler SMI is accounted for

## Integration Instructions

- N/A

### CODE REVIEW

**Comment by lgao4** [comment]
Co-authored-by can be removed, because Co-authored-by is same to signed-off-by

**Comment by makubacki** [comment]
> Co-authored-by can be removed, because Co-authored-by is same to signed-off-by

These are some older changes we've had that have been squashed and updated in their transition to edk2. That's being used here more to indicate that changes were made by [both authors](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) to content in the commit versus the Developer Certificate of Origin (the sign off).

**Comment by makubacki** [comment]
@lgao4 & @jyao1 can you please review this when you get a chance?

**Comment by makubacki** [comment]
> @lgao4 & @jyao1 can you please review this when you get a chance?

Friendly reminder. Thanks!

**Review by lgao4 — APPROVED** [review]

**Comment by makubacki** [comment]
@lgao4, are you okay to add the push label now?

**Comment by makubacki** [comment]
> @lgao4, are you okay to add the push label now?

I'm going to add the push label since this has maintainer approval. Thanks for your review.

**Comment by makubacki** [comment]
@mergify refresh

**Comment by makubacki** [comment]
@mergify queue

**Comment by makubacki** [comment]
@mergify rebase

**Comment by makubacki** [comment]
@mergify refresh

**Pull request merged**
