### PR TITLE
Basetools x86 pie relocs

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
Yet another alternative approach to fix the GOT handling on x86_64

This supersedes #6355 but is more intrusive.

@mikebeaton

### CODE REVIEW

**Comment by mikebeaton** [comment]
CLANGPDB and GCC seem to be okay, but CLANGDWARF is not working. X64 NOOPT build does not start (not even repeating the single early debug print line as previously). X64 DEBUG build gives this:

```
$ ./build.sh -a X64 -b DEBUG -t CLANGDWARF qemu -serial stdio -fw_cfg name=opt/org.tianocore/X-Cpuhp-Bugcheck-Override,string=yes
Building from: /home/mjsbeaton/OpenSource/edk2
using prebuilt tools
Running: qemu-system-x86_64 -drive if=pflash,format=raw,file=/home/mjsbeaton/OpenSource/edk2/Build/OvmfX64/DEBUG_CLANGDWARF/QEMU/bios.bin -serial stdio -fw_cfg name=opt/org.tianocore/X-Cpuhp-Bugcheck-Override,string=yes
SecCoreStartupWithStack(0xFFFCC000, 0x820000)
Unable to GetInfo for GUIDed section
Unable to find PEI Core image
ASSERT [SecMain] PeCoffGetEntryPoint.c(158): Pe32Data != ((void *) 0)
```

**Comment by ardbiesheuvel** [comment]
> CLANGPDB and GCC seem to be okay, but CLANGDWARF is not working. OvmfPkg X64 NOOPT build does not start (not even repeating the single early debug print line as previously). X64 DEBUG build gives this:
> 
> ```
> $ ./build.sh -a X64 -b DEBUG -t CLANGDWARF -D DEBUG_ON_SERIAL_PORT
> [...snip...]
> $ ./build.sh -a X64 -b DEBUG -t CLANGDWARF qemu -serial stdio
> Building from: /home/mjsbeaton/OpenSource/edk2
> using prebuilt tools
> Running: qemu-system-x86_64 -drive if=pflash,format=raw,file=/home/mjsbeaton/OpenSource/edk2/Build/OvmfX64/DEBUG_CLANGDWARF/QEMU/bios.bin -serial stdio -fw_cfg name=opt/org.tianocore/X-Cpuhp-Bugcheck-Override,string=yes
> SecCoreStartupWithStack(0xFFFCC000, 0x820000)
> Unable to GetInfo for GUIDed section
> Unable to find PEI Core image
> ASSERT [SecMain] PeCoffGetEntryPoint.c(158): Pe32Data != ((void *) 0)
> ```

Just checking: did you rebuild the BaseTools?

**Comment by ardbiesheuvel** [comment]
In any case, I am going to merge #6355 as it is a minimal fix that addresses an actual known build problem. I'd still like to move away from --emit-relocs in the future, but that doesn't need to happen in right now.

**Comment by mikebeaton** [comment]
> Just checking: did you rebuild the BaseTools?

Yes of course.

**Comment by ardbiesheuvel** [comment]
> using prebuilt tools

Right. I spotted the `using prebuilt tools` in your comment so I had to double check.

In any case, I've merged #6355 - I will revisit this later. Thanks for testing.

**Pull request closed without merging**
