### PR TITLE
Pr mpcore plusplus

### PR DESCRIPTION
**Pull request by ardbiesheuvel**

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
@mdkinney @makubacki @leiflindholm another example with weird CI errors:
- uncrustify fails but won't tell me on which file
- EccCheck flags an error in EmbeddedPkg which is not modified by any of the patches

**Comment by Javagedes** [comment]
@ardbiesheuvel Which pipeline job is not showing you the reason Uncrustify Failed?

Reviewing the `results.xml` is showing me the Uncristify failure that is happening in ARM_ARMPLATFORM for both the Ubutnu and Windows runs:

```
 Formatting errors in PeilessSec\PeilessSec.h
 --- D:\a\1\s\ArmPlatformPkg\PeilessSec\PeilessSec.h
 +++ D:\a\1\s\ArmPlatformPkg\PeilessSec\PeilessSec.h.uncrustify_plugin
 @@ -28,7 +28,6 @@
 #include &lt;Ppi/ArmMpCoreInfo.h&gt;
 #include &lt;Ppi/GuidedSectionExtraction.h&gt;
 #include &lt;Ppi/SecPerformance.h&gt;
 -
 
 extern UINT64  mSystemMemoryEnd;
```

[Artifacts](https://dev.azure.com/tianocore/edk2-ci/_build/results?buildId=141587&view=artifacts&pathAsName=false&type=publishedArtifacts)/Build Logs TARGET_ARM_ARMPLATFORM/TestSuites.xml

**Comment by Javagedes** [comment]
@ardbiesheuvel  As for the Ecc check failure, did you happen to branch this PR off of the branch in #5969? All the files it's complaining about are files you deleted in that PR. Ecc check only runs on files changes between the PR branch and main. If you happened to branch off of that PR, it could be picking up those files in the diff, and since they are not deleted in this PR, it's able to run Ecc on them and catching a bunch of compliance failures that have not been caught before because no one touched those components.

**Comment by ardbiesheuvel** [comment]
> @ardbiesheuvel Which pipeline job is not showing you the reason Uncrustify Failed?
> 

The uncrustify diff used to be attached in the Azure UI somewhere, but this is no longer the case.

> Reviewing the uploaded `TestSuites.xml` for the job run is showing me the Uncrustify failure that is happening in ARM_ARMPLATFORM for both the Ubutnu and Windows runs while Build_GCC5 TARGET_GCC_ONLY does not have an Uncrustify Failure:
> 

How do I locate this link from the PR page?

> You can also add `UNCRUSTIFY_IN_PLACE=TRUE` to your `stuart_ci_build` command to fix any issues automatically.

I don't use stuart.

> @ardbiesheuvel As for the Ecc check failure, did you happen to branch this PR off of the branch in #5969? Even if not, you are not rebased at the top of master, and probably behind #5969. All the files it's complaining about are files you deleted in that PR. Ecc check only runs on files changes between the PR branch and master. If you happened to branch off of that PR, it could be picking up those files in the diff, and since they are not deleted in this PR, it's able to run Ecc on them and catching a bunch of compliance failures that have not been caught before because no one has touched those components in a long time. But you don't see it in the actual PR because github is smarter than git in terms of what it shows you in the PR.
> 

This sounds plausible. However, the diff I expect the CI to operate on is the diff of all the patches in the PR combined., nothing else. When it manages to construct some other diff and reject it based on changes that are not being proposed, I consider this a bug in the CI.

> From my understanding git diff takes into context the common ancestor between two branches and will return all changes in both branches from where they split to where they are now.
> 
> github is a bit smarter and actually says "hey, these two commits, while they are different shas, are actually the same change, so I'm going to ignore them in this PR".
> 
> So while github PR is not showing that diff, git diff does see it, which is what is triggering EmbeddedPkg to build, and fail.
> 

Again, sounds plausible. But that doesn't make it correct or sane.

> 
> With all of that said, rebasing your branch to top of master should fix it.

Thanks, although I feel this shouldn't be necessary.

**Comment by Javagedes** [comment]
> The uncrustify diff used to be attached in the Azure UI somewhere, but this is no longer the case.

Got it, will investigate.

> How do I locate this link from the PR page?
Click the name of the job to show the general information about it, then click on artifacts. From there just navigate to the correct job artifact folder.
image

> I don't use stuart.

Sure, that is your choice, just letting you know it is an option

> Again, sounds plausible. But that doesn't make it correct or sane.

Sure, I get that, and can look into it.

> Thanks, although I feel this shouldn't be necessary.

I agree, it should not be necessary for these two CI Checks, yes; However, for the overall correctness of continuous integration checks for your change (mainly the package builds), we should always be running changes against the top of the branch we are merging into, so we make sure any changes merged before your change, do not conflict or break your change. This is why mergify does a final rebase before running CI on a PR in the merge queue.

**Comment by Javagedes** [comment]
> But this also does not really explain why the CI brings back a couple of deleted files to run CI check against, does it?

I'm fairly certain this is the whole git diff / github view I mentioned - though it's speculative at this point, and I agree that it is an issue that I will be looking into, along with the test results for uncrustify not showing up in the UI :)

**Comment by ardbiesheuvel** [comment]
> > But this also does not really explain why the CI brings back a couple of deleted files to run CI check against, does it?
> 
> I'm fairly certain this is the whole git diff / github view I mentioned - though it's speculative at this point, and I agree that it is an issue that I will be looking into, along with the test results for uncrustify not showing up in the UI :)

Thanks a lot for taking the time.

**Pull request closed without merging**
