### PR TITLE
[edk2-devel] [PATCH] OvmfPkg/X86QemuLoadImageLib: fix "unused variable" error in X64 DXE builds -- push

### PR DESCRIPTION
**Pull request by lersek**
https://bugzilla.tianocore.org/show_bug.cgi?id=2572
https://edk2.groups.io/g/devel/message/55622
http://mid.mail-archive.com/20200306230442.24100-1-lersek@redhat.com

### CODE REVIEW

**Comment by lersek** [comment]
Sigh, mergifybot is again not picking up the "push" label, after successful CI checks. Closing and reopening, I guess...

**Comment by lersek** [comment]
This is incredibly annoying.

**Comment by lersek** [comment]
Ticket ID: 592107.

**Comment by spbrogan** [comment]
@Mergifyio refresh

**Comment by spbrogan** [comment]
@mdkinney  or @lersek  can one of you try commenting with the mergifyio refresh syntax.  Looks like Mergifyio has missed that the builds are passing.

**Comment by mdkinney** [comment]
"@Mergifyio refresh

**Comment by spbrogan** [comment]
@lersek  - when you create the PR there is a checkbox at the bottom.  Did you have that checked?  

image

**Comment by lersek** [comment]
@spbrogan I always uncheck that box.

**Comment by lersek** [comment]
Anyway the patch has been merged via Ard's #427, closing this one.

Thanks for the help. I'll remember `@Mergifyio refresh` for the next time.

**Pull request closed without merging**
