### PR TITLE
AMD SEV Debugswap

### PR DESCRIPTION
**Pull request by aik**
This is to prevent #DB interception on AMD SEV-ES VM with enabled DebugSwap feature.

The goal of this pull request is CI check, attempt 4.

### CODE REVIEW

**Review by ardbiesheuvel — COMMENTED** [review]
Please fix the typo in the patch title OvmfPkf->OvmfPkg. Also, there are two OvmfPkg patches with similar names that do different things, so please try to be more descriptive.

**Comment by aik** [comment]
> Please fix the typo in the patch title OvmfPkf->OvmfPkg. Also, there are two OvmfPkg patches with similar names that do different things, so please try to be more descriptive.

I'm fixing the typo but I cannot figure out better subject lines. Which two do you want to differ more? thanks,

**Review by ardbiesheuvel — APPROVED** [review]
Never mind the titles - let's keep them as they are.

**Comment by kraxel** [comment]
Looks good to me.

Note #1: this conflicts with another pending PR updating the AMD header files.

Note #2: I think @jyao1 should have a look at the PCD changes, whenever there are any concerns from TDX point of view (probably not), and whenever TDX has a simliar feature so it might make sense to define a common attr bit for that (maybe).

**Review by kraxel — APPROVED** [review]

**Review by tlendacky — APPROVED** [review]

**Comment by ardbiesheuvel** [comment]
@lgao4 @mdkinney @jyao1 any comments on this PR?

**Comment by aik** [comment]
ping?

**Comment by ardbiesheuvel** [comment]
@jyao1 @niruiyu Any thoughts? If not, I intend to merge this PR tomorrow.

**Pull request merged**
