### PR TITLE
More fallbacks + error handling in UefiShellLib

### PR DESCRIPTION
**Pull request by NicoHood**
Hi,
I am migrating an Efi program which uses filesystem access via the Efi Shell helpers to a program which works without the shell. Therefor You need to rename it to BootX64.efi and simply boot straight into it without a shell. I've also modified the entry point of there library (Simply placing another call in CEntryLib which calls the program without arguments).

The ShellLib handles filesystem access and covers most of the I/O functions with a fallback mode which works without efi. However there were a few things in the ShellLib which are not covered yet. The problems which I've found so far are:

Line 114: Unsafe call to ´mEfiShellEnvironment2->SESGuid´? (not fixed)
Line 246: FileFunctionMap can always be used as Fallback, even without Efi Shell (fixed)
Line 742: Unsafe call/assert to ´mEfiShellEnvironment2->NameToPath´ (fixed)
Line 4160: Unsafe call to ´gEfiShellProtocol->GetFilePosition´ (fixed)
Line 4247: Unsafe call to ´gEfiShellProtocol->GetHelpText´ (fixed)
ShellCEntryLib has no default function call without Efi Shell
Line 742 required a bigger change. I've looked up how this function works: The Efi Shell creates a map of all available filesystems (fs0: etc) and their equivalent device paths. This functions tries to finds this device device path of the device first. If no device is passed (fs0:file) it uses the current directory as device path. This device path is then merged with the device path of the file.

What I've changed now is that we do not have this mapping of the drives and also we have no "current directory". That's why I've used the Efi variables ´Bootcurrent´ and ´Boot####´ as alternative to get the device path of the boot device. That is where I expect my file if no Efi Shell is used.

The other changes are minor. I've just added some error handling, however I am not sure if the returned Errors are correct, you might want to change those. One unsafe call I haven't fixed, you should have a look at this. I've not posted the ShellCEntryLib change. Its quite simple and I am unsure if you want to add this. If yes, let me know.

It would be extremely cool if you could give me some feedback about the fixes I made. It would be great to use the ShellLib without Efi, especially because almost all functions already have a fallback except the one that I've fixed. If you have a better idea how to fix this function, let me know. I am all new to Efi programming so any new Ideas and help are welcome.

Thanks for taking the time.

### CODE REVIEW

**Comment by lersek** [comment]
Hi,

your analysis and intent to contribute is highly valued; github pull requests are not the way we do patch review however. Instead,

* please subscribe to the https://lists.01.org/mailman/listinfo/edk2-devel mailing list
* wait until your subscription completes,
* post your patches to edk2-devel,
* make sure you have the `Contributed-under` line above your `Signed-off-by` (see `ShellPkg/Contributions.txt`
* be sure to CC the ShellPkg maintainers on your patches -- please see them in `Maintainers.txt`

If the review is complete, and the ShellPkg maintainers agree, your branch *can* be pulled (merged) from your github repo. In other words, this is not against merging per se (maintainers are at liberty to accept emailed pull requests); the important part is that the patches must be posted to the list for review.

Thanks.

**Comment by lersek** [comment]
For more detail, see:

* (official guide) https://github.com/tianocore/tianocore.github.io/wiki/EDK-II-Development-Process
* (my personal recommendations) https://github.com/tianocore/tianocore.github.io/wiki/Laszlo's-unkempt-git-guide-for-edk2-contributors-and-maintainers

**Comment by NicoHood** [comment]
Thank you. I've posted it in the mailing list, however no response so far. I hope to get some review of this, as it would be extremly helpful for non efi shell programs which can be signed for secureboot then.

**Comment by lersek** [comment]
Hm, in retrospect I can indeed find your patch on the list:

`[edk2] [PATCH] ShellPkg: More fallbacks + error handling in UefiShellLib`
https://lists.01.org/pipermail/edk2-devel/2016-September/001439.html

But why do you say there hasn't been any feedback? I see this:
https://lists.01.org/pipermail/edk2-devel/2016-September/001453.html

If you'd like to continue discussing the patch (or just ping for further reviews), please ping on the list, CC'ing the maintainers from `Maintainers.txt`. Thanks!

**Pull request closed without merging**
