### PR TITLE
OvmfPkg: Move kernel hashes section to end

### PR DESCRIPTION
**Pull request by deeglaze**
When launching a SEV-SNP VM, the ROM is not all that must be measured. The OvmfSevMetadata sections describe ranges of memory that must be measured with different types than PAGE_TYPE_NORMAL, except one. The SevSnpKernelHashes page is also PAGE_TYPE_NORMAL, but is populated by the VMM from configuration data that is separate from the OVMF build itself. To more compactly provide reference values for the measurement of the firmware separately from the kernel hashes, it's advantageous to measure as much known information as possible first.

Whereas VMMs are permitted to measure these sections in any order they prefer, the normative order of how they appear in the .fd is easiest to follow. This change is semantics-preserving. Measurement calculation tools that do not follow the normative ordering would need updating to accommodate, but I don't know of any. The accounting for EC2 moving the CPUID page to the end of measurement would be unchanged.

This change is to improve performance of a proposed launch update event log to separate responsibility for initially measured data before VM launch, application/vnd.amd.sevsnp.launch-updates+cbor:

https://github.com/deeglaze/draft-deeglaze-amd-sev-snp-corim-profile

- [ ] Breaking change?
- [ ] Impacts security?
- [ ] Includes tests?

## How This Was Tested

Built and launched a SEV-SNP VM with the changed firmware.

## Integration Instructions

N/A

### CODE REVIEW

**Comment by tlendacky** [comment]
Is the idea to still do an SNP_LAUNCH_UPDATE of the kernel hashes, but just as the last metadata update, or no longer do the SNP_LAUNCH_UPDATE? Because looking at the patch, the kernel hashes information is now outside of the SNP metadata GUIDed struct and so the area containing the hashes will be not be measured anymore. I guess I'm just a bit confused...

**Comment by deeglaze** [comment]
Oh crumbs, good catch. No, the idea is still to measure it.

**Review by larrydewey — APPROVED** [review]
I manually tested these changes with [sev-snp-measure](https://github.com/virtee/sev-snp-measure), and generating the expected launch digest continues to work as expected.

**Review by tlendacky — APPROVED** [review]

**Review by ardbiesheuvel — APPROVED** [review]

**Comment by mdkinney** [comment]
@mergify rebase

**Comment by ardbiesheuvel** [comment]
@mergify rebase

**Pull request merged**
