### PR TITLE
MdePkg: extend BaseFdtLib with more exposed functions

### PR DESCRIPTION
**Pull request by leiflindholm**
# Description

In preparation for deleting the libfdt sort-of-integration in EmbeddedPkg, add missing interfaces to MdePkg BaseFdtLib to be able to move all of the current users in the main edk2 repo over.

This work sits on top of https://github.com/tianocore/edk2/pull/6263, and hence includes the two commits from that PR first.

It is split into slightly more commits than strictly necessary.

Finally add the currently unmaintained (by BaseFdtLib maintainers) files in MdePkg/Library/BaseFdtLib to Maintainers.txt, and add myself as a maintainer.

None of these changes (that aren't really a part of https://github.com/tianocore/edk2/pull/6263) break anything for existing users.

### CODE REVIEW

**Review by ChaselChiu — APPROVED** [review]

**Comment by leiflindholm** [comment]
Oops, maybe I should have set this one to draft (even though it wasn't) since it "depended on" (included) the patches from https://github.com/tianocore/edk2/pull/6263 which was not yet merged. I do wish github had dependency tracking on PRs.

If anyone feels like this should be reverted, I won't object.

Ping @gdong1 @Sean-StarLabs @jameslu8 @gguo11837463

**Comment by ChaselChiu** [comment]
> Oops, maybe I should have set this one to draft (even though it wasn't) since it "depended on" (included) the patches from #6263 which was not yet merged. I do wish github had dependency tracking on PRs.
> 
> If anyone feels like this should be reverted, I won't object.
> 
> Ping @gdong1 @Sean-StarLabs @jameslu8 @gguo11837463

I thought you have included #6263 in current PR#6272, is there any change still pending?
https://github.com/tianocore/edk2/commit/bf7dbf6380a5ae349bc833cd1d7378c3a78b718b

**Comment by leiflindholm** [comment]
> I thought you have included #6263 in current PR#6272, is there any change still pending? [bf7dbf6](https://github.com/tianocore/edk2/commit/bf7dbf6380a5ae349bc833cd1d7378c3a78b718b)

There is no change pending (#6263 got auto-closed when this PR was merged).

I did include the commits, but my intent, which I will be more clear about in the future, was for that PR to be merged first. We ended up not getting any review from UefiPayloadPkg maintainers, and we lost Benny's approval for that in the PR history.

**Comment by ChaselChiu** [comment]
> > I thought you have included #6263 in current PR#6272, is there any change still pending? [bf7dbf6](https://github.com/tianocore/edk2/commit/bf7dbf6380a5ae349bc833cd1d7378c3a78b718b)
> 
> There is no change pending (#6263 got auto-closed when this PR was merged).
> 
> I did include the commits, but my intent, which I will be more clear about in the future, was for that PR to be merged first. We ended up not getting any review from UefiPayloadPkg maintainers, and we lost Benny's approval for that in the PR history.

agree. I added push tag too soon. I will also wait for couple days next time.

**Pull request merged**
