### PR TITLE
.github: Add GitHub issue templates

### PR DESCRIPTION
**Pull request by makubacki**
# Description

REF:https://github.com/tianocore/edk2/discussions/5926

Adds GitHub form isssue templates for bugs, documentation requests, and feature requests.

These files define the form structure in YAML to be rendered by GitHub in the edk2 repo issues area.

See the referenced RFC for additional details.

Future changes will add automation tasks described in the RFC. These are expected in the next couple of days or so.

---

**Form previews:**

- [Bug](https://github.com/makubacki/edk2/issues/new?assignees=&labels=type%3Abug%2Cstate%3Aneeds-triage&projects=&template=bug_report.yml&title=%5BBug%5D%3A+%3Ctitle%3E)
- [Feature Request](https://github.com/makubacki/edk2/issues/new?assignees=&labels=type%3Afeature-request%2Cstate%3Aneeds-triage&projects=&template=feature_request.yml&title=%5BFeature%5D%3A+%3Ctitle%3E)
- [Documentation Request](https://github.com/makubacki/edk2/issues/new?assignees=&labels=type%3Adocumentation-request%2Cstate%3Aneeds-triage&projects=&template=documentation_request.yml&title=%5BDocumentation%5D%3A+%3Ctitle%3E)

---

- [ ] Breaking change?
- [ ] Impacts security?
- [ ] Includes tests?

## How This Was Tested

- Verify issue template functionality on edk2 fork.

## Integration Instructions

- N/A

### CODE REVIEW

**Comment by leiflindholm** [comment]
I strongly approve of the utf-8 fixes, but they don't feel related to the PR title, nor the commit that *is*.

**Comment by lgao4** [comment]
> I strongly approve of the utf-8 fixes, but they don't feel related to the PR title, nor the commit that _is_.

This chanage is also good to me.

**Comment by makubacki** [comment]
> I strongly approve of the utf-8 fixes, but they don't feel related to the PR title, nor the commit that _is_.

The files contain Unicode characters that cause the plugins to fail. I consider them a trivial tweak for this PR to pass CI. Having them in this PR ensures ordering - they go in before the templates.

To focus discussion in this PR though, I'll move them to a dedicated one. These templates will go in after the Bugzilla data has been moved to GitHub so that should provide ample time for the utf-8 PR to be completed.

**Comment by makubacki** [comment]
Plugin PR: https://github.com/tianocore/edk2/pull/6542

**Comment by leiflindholm** [comment]
> > I strongly approve of the utf-8 fixes, but they don't feel related to the PR title, nor the commit that _is_.
> 
> The files contain Unicode characters that cause the plugins to fail. I consider them a trivial tweak for this PR to pass CI. Having them in this PR ensures ordering - they go in before the templates.

I'm not opposed to that workflow, but it wasn't apparent to me from the PR description or commit messages that that was why they were there.

**Review by leiflindholm — APPROVED** [review]

**Comment by makubacki** [comment]
@mdkinney, I added a "code first" checkbox to each issue form.

**Review by mdkinney — APPROVED** [review]

**Pull request merged**
