### PR TITLE
[BZ-4655] MdeModulePkg/UfsBlockIoPei: Wait fDeviceInit Be Cleared by Devices

### PR DESCRIPTION
**Pull request by linjaso1**
# Description

- [Bugzilla#4655](https://bugzilla.tianocore.org/show_bug.cgi?id=4655)

- Changes
  - UFS device would clear fDeviceInit flag once the device initialization is completed.
  - This change is polling to check the flag is cleared or not with specific timeout (UFS_INIT_COMPLETION_TIMEOUT - 600ms).
  - This behavior is the same as UfsPassThruDxe module.
 
- Related Changes
  - 95ad8f7f6a6c84ef46a96a8ba852afed805d1ca3
  - c5740f360636479fb91681093b1dee1cc366075c

- [ ] Breaking change?
  - No, it is added the internal function within module only and code flow change

- [ ] Impacts security?
  - No, this change do not include any security-related change

- [X] Includes tests?
  - As per Bugzilla reported, the DXE module had been executed successfully
  - Port the fix into PEI module as-well

## How This Was Tested

- Check the UFS device could be initialized correctly in PEI phase

## Integration Instructions

- N/A.

### CODE REVIEW

**Comment by linjaso1** [comment]
Hi @niruiyu / @lgao4 ,

Could you help to review this PR?

Thanks.

**Comment by lgao4** [comment]
I have one comment on time out 600ms. How do you decide to choose this value?

**Comment by linjaso1** [comment]
600ms is the same defined in DXE module currently.

From that commit, I only got the info that some devices might take longer time.

I have plan to move into PCD value in next PR to let platform decide it.

In this patch, want to fill the gap between PEI and DXE first.

**Review by lgao4 — APPROVED** [review]

**Comment by lgao4** [comment]
This patch is good to me. I have no other comment.

**Pull request merged**
