### PR TITLE
Armpkg setway cache maintenance

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
# Description

Remove set/way d-cache maintenance from the ArmLib API. This will break Beagle unless https://github.com/tianocore/edk2-platforms/pull/194 is merged first.

### CODE REVIEW

**Review by leiflindholm — APPROVED** [review]

**Comment by mdkinney** [comment]
@mergify refresh

**Comment by mdkinney** [comment]
@mergify requeue

**Comment by mdkinney** [comment]
@mergify rebase

**Comment by mdkinney** [comment]
@mergify refresh

**Comment by ardbiesheuvel** [comment]
@mergify requeue

**Pull request merged**
