### PR TITLE
EmbeddedPkg: MDEPKG_NDEBUG fixes

### PR DESCRIPTION
**Pull request by mikebeaton**
# Description

Add -DMDEPKG_NDEBUG to EmbeddedPkg CC_FLAGS for RELEASE build. Although EmbeddedPkg normally provides components to other packages, it is less surprising if its own build defines MDEPKG_NDEBUG when consuming packages normally would.

Additionally remove MDEPKG_NDEBUG dependent code which is no longer needed given update of 'null' debug macros in ae83c6b7fd83a5906e016a32027c1bcd792a624e to explicitly mark debug-only code as discarded; correctly mark as STATIC the two arrays within the updated code block.

- [ ] Breaking change?
- [ ] Impacts security?
- [ ] Includes tests?

## How This Was Tested

Local build.

## Integration Instructions

N/A

### CODE REVIEW

**Comment by mikebeaton** [comment]
cc @leiflindholm - If I had correctly understood that the main purpose of EmbeddedPkg was to provide code to other packages, I would have included this change in 695660dd2ab15284c761a203d094bd444f78bb8a.

I did establish, when testing [that PR](https://github.com/tianocore/edk2/pull/6257), 1) that the build of EmbeddedPkg itself worked after those commits (because it didn't define MDEPKG_NDEBUG) and 2) that the affected code changed here isn't consumed by anything in EDK II. Therefore I felt it was best to address this issue separately, afterwards.

With hindsight, I believe that if any _external_ code is consuming MmcDxe (as some EDK II ARM packages used to do, but a while ago now), it would in fact now be broken until this additional commit is applied. I'm not sure if there is any such code, anywhere.

This is the only remaining change to MDEPKG_NDEBUG, in terms of checking for places where it is still used in C files, since the only other places it is still referred to in C code - after this change - are a whole seque4nce of AmlDebugPrint methods and associated support code in DynamicTablesPkg, and a conditional assert in MdePkg\Library\BaseLib\LinkedList.c, neither of which am I planning to change.

**Comment by sudeep-holla** [comment]
This needs to be merged ASAP as my build for VExpress fails. After this is merged, it still fails and need similar change in
Platform/ARM/VExpressPkg/Library/ArmVExpressPciHostBridgeLib/ArmVExpressPciHostBridgeLib.c to drop #ifdef similar to second patch here. Not sure what is the correct fix.

**Comment by sudeep-holla** [comment]
Adding @samimujawar for VExpress package build failure.

**Comment by mikebeaton** [comment]
> This needs to be merged ASAP as my build for VExpress fails. After this is merged, it still fails and need similar change in Platform/ARM/VExpressPkg/Library/ArmVExpressPciHostBridgeLib/ArmVExpressPciHostBridgeLib.c to drop #ifdef similar to second patch here. Not sure what is the correct fix.

@sudeep-holla - You can just remove the `#ifdef` and `#endif` at this one location and the package builds, I just tested.

> Hi @mikebeaton, would it make sense to also update the following macros:
> 
> ```
> MdePkg/Library/BaseLib/LinkedList.c::ASSERT_VERIFY_NODE_IN_VALID_LIST()
> MdePkg/Include/Library/UefiLib.h::ASSERT_LOCKED()
> MdePkg/Include/Library/DebugLib.h::ASSERT_PROTOCOL_ALREADY_INSTALLED()
> ```

I spotted these, they all refer to things that cannot possibly be undefined so I left them as they are.

> The `MDEPKG_NDEBUG` in the DynamicTablesPkg should be ok.

Agreed.

> I am going to send a patch for the `edk2-platforms` repo for the arm related part, but I think it would be good to check the other parts of the package as well

I clearly need to look at this asap - there aren't too many of these, so I am happy to make a PR addressing them all, including the ARM platform ones?

**Review by leiflindholm — APPROVED** [review]

**Comment by mikebeaton** [comment]
@sudeep-holla @pierregondois Are you able to confirm that https://github.com/tianocore/edk2-platforms/pull/230 fixes the issues in edk2-platforms for you?

**Comment by pierregondois** [comment]
Yes it works for me, thanks!

**Pull request merged**
