### PR TITLE
Maintainers: Remove Ard Biesheuvel from all packages

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
As a Tianocore maintainer, I am responsible for the packages that I maintain, and am therefore expected to respond in a timely manner to pull requests affecting those packages. With the updated GitHub-based workflow, this now results in daily GitHub spam inviting me to respond to each PR as they are created by the respective authors.

However, I strongly feel that with responsibility, delegated authority should come as well, and this has been stripped away over the past couple of years. When other maintainers fail to respond (which has become more common recently), or when there are glitches in the CI, I no longer have any means to take charge and correct the situation.

The upshot is that I am struggling to do my work as a maintainer, spending 90% of my time dealing with GitHub CI technicalities, or being blocked on other work that is completely ignored by the other maintainers.

This is a waste of my time, and therefore, of my employer's money, so I feel I can no longer justify my involvement. I am therefore stepping down as a maintainer.

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
cc @os-d @spbrogan @samimujawar @pierregondois

**Comment by ardbiesheuvel** [comment]
cc @kraxel

**Review by leiflindholm — APPROVED** [review]
While obviously sorry to hear this, I fully understand.
Thank you for all your contributions over the years.

@samimujawar this obviously leaves a pretty big gap on the Arm side, and it leaves ArmVirtPkg completely without maintainers. Could you have a chat internally about how to address this?

**Comment by ardbiesheuvel** [comment]
cc @lgao4

**Comment by kraxel** [comment]
> While obviously sorry to hear this, I fully understand. Thank you for all your contributions over the years.

You will be missed.

> @samimujawar this obviously leaves a pretty big gap on the Arm side, and it leaves ArmVirtPkg completely without maintainers. Could you have a chat internally about how to address this?

Leaves a gap for OvmfPkg too, with the most active maintainer leaving.
@jyao1

**Comment by ardbiesheuvel** [comment]
Thanks all for the kind words.

> You were definitely the most active maintainer with thoughtful and insightful feedback, as well as major code contributions. Let us know if we can help drive some change that would encourage you to come back.

The only thing I ever asked for several times, and was denied each time, is the ability for maintainers to override the CI. Without that, the CI's decision takes precedence over that of human maintainers, turning it into a super maintainer with more control over the project than the actual contributors.

I'll gladly reconsider if that gets resolved.

**Comment by samimujawar** [comment]
Ard’s been immensely valuable contributor to the Tinacore projects over the years. His unique experience of working on kernel development, security and other firmware projects has meant the Tinacore project support for the Arm ecosystem is a much better place than it would have been.  Whilst, respecting Ard’s personal decision, his withdrawal leaves gaps that is not possible to solve in the short to medium. Personally, I am disappointed and frustrated it’s got to a point a willing key maintainer is not able to be productive and carry out their day-to-day maintainership due to the limitations of the CI and workflow. Why can’t these issue be taken more seriously and addressed? Let’s listen to Ard’s concerns and try to fix these issues as any replacement coming through is also likely face the same set of problems.  I am willing to take on additional maintainer/reviewer responsibility in a gradual manner, but I would really like the community to help address Ard’s concerns and look at what can be done to fix that first.

**Comment by leiflindholm** [comment]
@samimujawar 
> Why can’t these issue be taken more seriously and addressed?

For the usual reason: resources.
Is Arm willing to commit resources for the substantial effort required to 1) keep a CI system running and 2) implement the changes required for the system to not get in the way?

That's probably not a topic for a PR though.

**Comment by mdkinney** [comment]
I agree that the concerns about CI and a discussion of possible solutions can be moved to a different location.

One option is the GitHub discussion has been started for the CI/Tools meeting on Sept 30.
* https://github.com/tianocore/edk2/discussions/6208

There are links in there to additional discussions for CI improvement ideas and the transition to GitHub issues.

Another option is a thread on devel@edk2.groups.io

**Pull request merged**
