### PR TITLE
Add RngDxe to OVMF, with runtime check for rdrand

### PR DESCRIPTION
**Pull request by kraxel**
# Description

Add runtime check for the presence of the rdrand cpu instruction.
* CheckRdrandX64Dxe does the actual check and installs a protocol of present.
* CheckRdrandX64Lib depends via depex on the protocol and can be linked to modules which use rdrand.
* RndDxe module (with CheckRdrandX64Lib) is added to OVMF as alternative EFI_RNG_PROTOCOL driver in case virtio-rng is not available.

## How This Was Tested

* Check whenever network boot (which depends on EFI_RNG_PROTOCOL since 2024-05 stable tag) works.
* Inspect OVMF logfiles.

## Integration Instructions

N/A

### CODE REVIEW

**Comment by kraxel** [comment]
paging maintainers + reviewers: @ardbiesheuvel,@ruleof2,@jyao1,@mdroth,@mxu9,@tlendacky

**Comment by ardbiesheuvel** [comment]
cc @pierregondois 

This seems like a lot of hassle to work around the fact that `ArchIsRngSupported()` returns TRUE on x86 systems that do not implement RDRAND. Couldn't we fix that instead?

**Comment by ardbiesheuvel** [comment]
@bcran

**Comment by kraxel** [comment]
> cc @pierregondois
> 
> This seems like a lot of hassle to work around the fact that `ArchIsRngSupported()` returns TRUE on x86 systems that do not implement RDRAND. Couldn't we fix that instead?

Note that OVMF is probably the only case where runtime detection actually matters.  When building firmware for a physical platform you know what CPU you are going to use and whenever it has rdrand or not ...

Also we might add some more checks to `CheckRdrandX64Dxe`, @heatd mentioned there are some CPUs with known-bad rdrand implementations.  There is the obvious canevat that cpuid in a VM might not reflect the /real/ CPU identity.

**Comment by heatd** [comment]
> > cc @pierregondois
> > This seems like a lot of hassle to work around the fact that `ArchIsRngSupported()` returns TRUE on x86 systems that do not implement RDRAND. Couldn't we fix that instead?
> 
> Note that OVMF is probably the only case where runtime detection actually matters. When building firmware for a physical platform you know what CPU you are going to use and whenever it has rdrand or not ...
> 
> Also we might add some more checks to `CheckRdrandX64Dxe`, @heatd mentioned there are some CPUs with known-bad rdrand implementations. There is the obvious canevat that cpuid in a VM might not reflect the /real/ CPU identity.

I'd wager that you should sanely throw all of this into ArchIsRngSupported. It should have minimal size impact (and we could add a PCD to force enable it/enable autodetection if need be).

> There is the obvious canevat that cpuid in a VM might not reflect the /real/ CPU identity

I don't see what your point is? If you do -cpu host,+rdrand on a rdrand-less CPU (does qemu even take this? doesn't seem to on my end), this is PEBKAC IMO.

Unless you mean doing detection of these issues using CPUID strings or family/models, which is *not* my idea. This was my original patch: https://openfw.io/edk2-devel/20221122223103.597984-1-pedro.falcato@gmail.com/

**Pull request closed without merging**
