### PR TITLE
Smm cpu sync timeout

### PR DESCRIPTION
**Pull request by jiaxinwu**

### CODE REVIEW

**Comment by jiaxinwu** [comment]
@niruiyu @kraxel @jyao1 could you help review this patch?

**Comment by jiaxinwu** [comment]
Add PcdCpuSmmApSyncTimeout2 PCD
Provide the capability for platform to specifies the 2nd
timeout value in microseconds for the BSP/AP in SMM to wait for
one another to enter SMM.

The added interface can enhance the flexibility of timeout
configuration. In some cases, certain processors may not be
able to enter SMI, and prolonged waiting could lead to
kernel soft/hard lockup. We have now defined two timeouts.
The first timeout can be set to a smaller value to reduce
the waiting period. Processors that are unable to enter SMI
will be woken up through SMIIPL to enter SMI, followed by
a second waiting period. The second timeout can be set to a
larger value to prevent delays in processors entering SMI
case due to the long instruction execution.

**Review by niruiyu — APPROVED** [review]

**Review by ardbiesheuvel — APPROVED** [review]

**Review by kraxel — APPROVED** [review]

**Comment by rkrajkum** [comment]
Please do not check in this change to the TRUNK until WW30 (as both BRANCH & TRUNK share same EDK2 repo) as described in offline mails and HSD. BRANCH is frozen for any more FR changes.

**Comment by ardbiesheuvel** [comment]
> Please do not check in this change to the TRUNK until WW30 (as both BRANCH & TRUNK share same EDK2 repo) as described in offline mails and HSD. BRANCH is frozen for any more FR changes.

I have no idea what TRUNK, WW30, FR or HSD means, and I did not see any offline mails. Could you please elaborate?

**Review by ardbiesheuvel — APPROVED** [review]

**Comment by fli24** [comment]
Are we experiencing CI instability issue? Some checks are not completed even after long time. Thanks!

**Comment by jiaxinwu** [comment]
> Are we experiencing CI instability issue? Some checks are not completed even after long time. Thanks!

pass all check after rebase!

**Pull request merged**
