### PR TITLE
edksetup.sh: Fix the Issue of PYTHON_COMMAND Un-Configurable

### PR DESCRIPTION
**Pull request by linjaso1**
# Description

- With the commit e6447d2a08f5ca585816d093e79a01dad3781f98 introduced, there do not have chance for caller to configure the ```PYTHON_COMMAND``` environment variable outside of this script.

- All the configured value would be assigned into ```python3``` forcedly, without checking the environment variable is set or not.

- This patch included the below changes,
  - Check the ```PYTHON_COMMAND``` is set or not before assigning the default value ```python3``` on it.
  - Rename the function naming into ```SetupPythonCommand``` to align its functionality.

- [ ] Breaking change?
  - No, this change kept the default behavior of the ```PYTHON_COMMAND```.
  - Unless the caller assigned the variable outside of script, it would not break any change.

- [ ] Impacts security?
  - No, this change do not include any security-related change.

- [X] Includes tests?
  - This change passed the EDK-II CI build without any issue.

## How This Was Tested

- Check the ```PYTHON_COMMAND``` assigned manually by caller, the value could be preserved without any change.

- Check the ```PYTHON_COMMAND``` not set by caller, the value could be assigned as ```python3``` value.

## Integration Instructions

- Assigned the ```PYTHON_COMMAND``` before calling this the ```edksetup.sh``` script.
- Ensure the customized ```PYTHON_COMMAND``` is valid on the environment for code building.

### CODE REVIEW

**Comment by linjaso1** [comment]
Hi @ajfish / @leiflindholm  / @mdkinney ,

Could you help to review this PR?

Thanks,
Jason.

**Review by lgao4 — APPROVED** [review]

**Comment by dhaval-rivos** [comment]
Hi @linjaso1 in my bash environment with set -u (unbound variable check enabled) I get this error: edksetup.sh: line 111: PYTHON_COMMAND: unbound variable.
I am not a Python  expert but do we need something like this:
 # Set a default Python command if PYTHON_COMMAND is not set
  PYTHON_COMMAND=$(which python3 2>/dev/null || which python 2>/dev/null)

**Comment by linjaso1** [comment]
Hi @dhaval-rivos ,

In some cases, we do not always use the latest version of Python.
Especially in POSIX-based systems, the built-in version of Python is not always the intended one.
Your change is well-handling on assigning default values, but it no longer allows for external control from outside the script.

Meanwhile, there have the others unbounded variables like ```WORKSPACE``` inside this script as-well.
If you intended to enable that checking, it would be better to handle it as the others variables as-well.

Thanks.

**Comment by ajfish** [comment]
The code is just checking if PYTHON_COMMAND exists and if it does not exist it sets it to python3. The point of PYTHON_COMMAND is you can override which version of Python you are using. 

It looks like your global set -u breaks the probe
1) It looks like there was an update to make this script more POSIX compatible and less bash centric. I’m not clear on how that impacts set -u?
    a) Maybe we could: PYTHON_COMMAND=${PYTHON_COMMAND:-python3}

But I’m not an expert at the bash/POSIX shell programming thing….


SetupPythonCommand()
{
  #
  # If PYTHON_COMMAND is already set, then we can return right now
  #
  if [ -n "$PYTHON_COMMAND" ]
  then
    return 0
  fi

  export PYTHON_COMMAND=python3
}


https://github.com/tianocore/edk2/blob/master/edksetup.sh#L111

Thanks,

Andrew Fish

> On Nov 5, 2024, at 7:49 AM, Dhaval Sharma ***@***.***> wrote:
> 
> 
> Hi @linjaso1 <https://github.com/linjaso1> in my bash environment with set -u (unbound variable check enabled) I get this error: edksetup.sh: line 111: PYTHON_COMMAND: unbound variable.
> I am not a Python expert but do we need something like this:
> 
> Set a default Python command if PYTHON_COMMAND is not set
> 
> PYTHON_COMMAND=$(which python3 2>/dev/null || which python 2>/dev/null)
> 

I don’t think we want to change the behavior in this way. This moves setting Python path as a thing in your PATH. The existing code lets you set PYTHON_COMMAND independent of the PATH. So this would regress some of the previous functionality.

**Comment by dhaval-rivos** [comment]
Yes my colleague also suggested something similar which seem to work:
SetupPythonCommand()
{
  #
  # If PYTHON_COMMAND is already set, then we can return right now
  #
  if [ -n "${PYTHON_COMMAND:-}" ]
  then
    return 0
  fi

  export PYTHON_COMMAND=python3
}
You guys okay with that?

**Comment by linjaso1** [comment]
If the change could keep its functionalities as-is, it shall be acceptable, but need to review by the correspond maintainers and reviewers.

From my viewpoint, the question would be if the community consider to enable the unbound variable checking by default or not rather than if fine for the above change.

If the answer is yes, than it shall be record in the whole repository and the code change shall be overall review in all of the shell scripts.

However the problem is our repository would include others open-source code as submodule, what if the script we calling into is not enabled it as-well, there would have the concern on it.

**Pull request merged**
