### PR TITLE
ArmVirtPkg: Resolve RngLib via RngDxe for TRNG support

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
Gerd reports that ArmVirtQemu running under KVM lost network boot support on systems that do not implement the RNDR/RNDRRS system registers, which provide an architectural, CPU-based source of random numbers. Under KVM, the TRNG SMCCC is available as a fallback, which is exposed via RngDxe but not via the base RngLib library. This means that direct users of RngLib, such as OpensslLib, have no access to the TRNG based entropy source.

Let's fix this by resolving RngLib dependencies via DxeRngLib, which uses the protocol exposed by RngDxe internally. In order to avoid creating a circular dependency, this requires the original RngLib resolutions to be provided to RngDxe specifically.

### CODE REVIEW

**Comment by pierregondois** [comment]
I think the following should be done for Qemu platforms:

```
 [LibraryClasses.common.PEIM]
   ArmVirtMemInfoLib|ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLib.inf
+!if $(ARCH) == AARCH64
+      RngLib|MdePkg/Library/BaseRngLib/BaseRngLib.inf
+!else
+      RngLib|MdePkg/Library/BaseRngLibTimerLib/BaseRngLibTimerLib.inf
+!endif
 
```

**Comment by ardbiesheuvel** [comment]
> I think the following should be done for Qemu platforms:
> 
> ```
>  [LibraryClasses.common.PEIM]
>    ArmVirtMemInfoLib|ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLib.inf
> +!if $(ARCH) == AARCH64
> +      RngLib|MdePkg/Library/BaseRngLib/BaseRngLib.inf
> +!else
> +      RngLib|MdePkg/Library/BaseRngLibTimerLib/BaseRngLibTimerLib.inf
> +!endif
>  
> ```

Indeed - I forgot to do a build test with `TPM2_ENABLE`

**Review by kraxel — APPROVED** [review]

**Comment by ardbiesheuvel** [comment]
@kraxel I simplified this substantially so it only applies to UEFI_DRIVERs such as TlsDxe. (The previous revision broke the boot tests in the CI because of some circular dependency with -D SECURE_BOOT_ENABLE)

**Comment by pierregondois** [comment]
Note:
`ArmVirtXen.fdf` doesn't install any `EFI_RNG_PROTOCOL`, but also doesn't seem to use the RngLib,
so everything seems good

**Review by pierregondois — APPROVED** [review]

**Pull request merged**
