### PR TITLE
UefiPayloadPkg: Fix S4

### PR DESCRIPTION
**Pull request by Sean-StarLabs**

### CODE REVIEW

**Review by gguo11837463 — APPROVED** [review]

**Comment by benjamindoron** [comment]
Is that the same variable size issue we discussed on coreboot's Gerrit? SMMSTORE requires `gEfiMdeModulePkgTokenSpaceGuid.PcdMaxVariableSize|0x8000`.

Though it would be interesting if it was the same coreboot and EDK2 commit and build configuration.

**Comment by Sean-StarLabs** [comment]
> Is that the same variable size issue we discussed on coreboot's Gerrit? SMMSTORE requires gEfiMdeModulePkgTokenSpaceGuid.PcdMaxVariableSize|0x8000.

Yes, but seems it was a red herring (0x8000 only asserts for debug builds). The behaviour is that edk2 will reset when trying to start the EFI SHell or an OS.

**Comment by benjamindoron** [comment]
> > Is that the same variable size issue we discussed on coreboot's Gerrit? SMMSTORE requires gEfiMdeModulePkgTokenSpaceGuid.PcdMaxVariableSize|0x8000.
> 
> Yes, but seems it was a red herring (0x8000 only asserts for debug builds). The behaviour is that edk2 will reset when trying to start the EFI SHell or an OS.

This is unfortunately a common misconception, due to the complexity of the debug stack. I should probably document it somewhere. The assert statement is 'reached' in release builds too, except around the tree, RELEASE tends to imply MDEPKG_NDEBUG, which strips all the debug macros - search for this define in the [DebugLib header](https://github.com/tianocore/edk2/blob/master/MdePkg/Include/Library/DebugLib.h). This doesn't have to be the case, see the enablement of UefiPayloadPkg's [CbSerialPortLib](https://github.com/tianocore/edk2/commit/f26b70cb9f1367ceb25190ba2777631ee42c69fe#diff-46ea4883eee85646f25a4e5732ffb1a8ee2447bffdf3aba462d0f9e1ab58e301).

Platforms can also customise the behaviour of the debug macros with `gEfiMdePkgTokenSpaceGuid.PcdDebugPropertyMask`: the defaults tend to be `DEBUG()` and fatal `ASSERT()` - sometimes `DEBUG_CODE()` for added code helping validation - but this also doesn't have to be the case, see this PCD used in one [DebugLib instance](https://github.com/tianocore/edk2/blob/1436aea4d5707e672672a11bda72be2c63c936c3/MdeModulePkg/Library/PeiDxeDebugLibReportStatusCode/DebugLib.c#L481-L485). For CbSerialPortLib, stalling the platform didn't make sense, so we keep the high nybble of the PCD clear.

On devices with TBT, it was by design, but I'm not sure now. The point of this patchseries is to ultimately provide the OS with what EDK2 might consider a 'good' memory map, even if it wants a reset. I think we should reconsider restoring the change to the `gEfiMdeModulePkgTokenSpaceGuid.PcdResetOnMemoryTypeInformationChange` line. But perhaps my MemoryTypeInformation values are incorrect for some platforms, please check a debug log for lines including the following, and we'll determine better values:
```
Memory  Previous  Current    Next   
 Type    Pages     Pages     Pages  
======  ========  ========  ========
[...]
Memory Type Information settings change.
```

We should still consider a case where the PCD data is too small. Two things to be mindful of:
- If emulated variables are used, no runtime updates are possible.
- The DxeCore gets *a* HOB. It's typical to try to read the variable and pass the contents as a HOB, because this will have the runtime updates (see [DxeIpl](https://github.com/tianocore/edk2/blob/1436aea4d5707e672672a11bda72be2c63c936c3/MdeModulePkg/Core/DxeIplPeim/DxeLoad.c#L364-L395) and MinPlatform's [PlatformInitPreMem](https://github.com/tianocore/edk2-platforms/blob/b6f96743891be51541184bf61dd2970c008e2c43/Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/PlatformInitPreMem.c#L159-L202)). But UefiPayloadPkg's UefiPayloadEntry doesn't have variable services. So, I'm concerned that attempting a runtime update would cause a boot-loop.

Well, long story short:
- The SMMSTORE issue still needs to be fixed, common RELEASE builds hide bugs.
- Let's update the PCD memory type info, and;
- Let's consider the impact of `PcdResetOnMemoryTypeInformationChange`. We want both correctness for S4, but also have to avoid boot-loops. Maybe a new `PcdWarnOnMemoryTypeInformationChange` is right, here?

**Comment by Sean-StarLabs** [comment]
Gotcha. This is the output from adl:
```
Memory  Previous  Current    Next
 Type    Pages     Pages     Pages
======  ========  ========  ========
  09    00000012  00000014  00000019
  0A    00000004  00000000  00000004
  00    00000004  00000006  00000007
  06    00000100  0000004F  00000100
  05    00000100  00000043  00000100
Memory Type Information settings change.

```

**Comment by benjamindoron** [comment]
That's the TBT platform with the issue, right? All this for 4 pages... Which is rather the point with `PcdResetOnMemoryTypeInformationChange` - there's no improvement on reset, because there are no variable services to use. Maybe we should document that.

Seems more space was needed than OVMF, I should have used BDS calculations I have generated. I can push a v2, or please increase:
- `gUefiPayloadPkgTokenSpaceGuid.PcdMemoryTypeEfiACPIReclaimMemory` to 0x19
- `gUefiPayloadPkgTokenSpaceGuid.PcdMemoryTypeEfiReservedMemoryType` to 0x8
- I'll also confirm this is good for my platform later.

It seems leaving `PcdResetOnMemoryTypeInformationChange` as-is, not performing reset, is required. I'll work on a `PcdWarnOnMemoryTypeInformationChange` feature at some point that warns the user that S4 resume may fail, and they should notify the platform maintainers, so that we mitigate this breakage in future. Most platforms just won't be compiling it in.

**Comment by Sean-StarLabs** [comment]
Thanks!

Yup.

Tested a TGL w/ TBT and GLK via ssh - both boot with those values. I'll give S4 a proper test on them on Tuesday.

**Comment by Sean-StarLabs** [comment]
> warns the user that S4 resume may fail

Just thinking out loud, it's been like this for 2.5+ year with coreboot, longer for SBL - and no-one noticed? Might not be worth the trouble ;)

**Comment by benjamindoron** [comment]
I wrote my findings in the commit messages. I've now found https://github.com/tianocore-docs/Docs/raw/master/White_Papers/A_Tour_Beyond_BIOS_Memory_Map_And_Practices_in_UEFI_BIOS_V2.pdf: "Memory Map in S4 resume – Memory Type Information" is a good explanation.

It confirms and explains most of what I found, and it seems the reason why this fixes S4 is because EDK2 passes one entry in the final memory map. But if the initial memory bins were insufficient, memory can be allocated outside them.

**Comment by Sean-StarLabs** [comment]
Which commit msgs?

**Comment by benjamindoron** [comment]
> Which commit msgs?

The commits of this series? https://github.com/tianocore/edk2/pull/4231/commits/ff30a5ccfa69ce35f44dc7b59f1e62d971aa2f03 has most of it.

```
MemoryType information assists GCD with defragmenting the memory map.
When the DXE core starts, GCD adds memory descriptors for the resource
descriptors HOBs. This allocates heap space which can be reused later
as the bins by memory type. It seems memory allocation prefers low
ranges.

It seems "below 4G" is an artifact of this heap reuse. However, the
memory type information determines the DXE core's
`MinimalMemorySizeNeeded`, determining which system memory descriptor
HOB may be used by DXE. Furthermore, it's important that the memory
type information be correct, for an S4 memory map.

Therefore, follow other bootloaders, such as [MinPlatform][1], and do
this unconditionally. As of [edk2-stable202011][2], it was.

[1]: https://github.com/tianocore/edk2-platforms/blob/b6f96743891be51541184bf61dd2970c008e2c43/Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/PlatformInitPreMem.c#L164-L201
[2]: https://github.com/tianocore/edk2/blob/edk2-stable202011/UefiPayloadPkg/BlSupportPei/BlSupportPei.c#L462-L466
```

**Comment by LeanSheng** [comment]
@gdong1 wonder if you have any feedback regarding this patch? as it will also affect SBL.

**Pull request merged**
