### PR TITLE
UefiPayloadPkg: FIT Image UPL

### PR DESCRIPTION
**Pull request by gguo11837463**
py -3 UefiPayloadPkg\UniversalPayloadBuild.py -t VS2019 -s 1.0
image

py -3 UefiPayloadPkg\UniversalPayloadBuild.py -t VS2019 -s 1.0 -DNETWORK_DRIVER_ENABLE=TRUE
image

### CODE REVIEW

**Comment by dhaval-rivos** [comment]
1. Do you expect BL to use PeiLoadFileLoadPayload PEI module? I would like to avoid using any PEIMs in UPL if possible. What if BL itself can find, load and relocate UPL?
2. gUniversalPayloadBaseGuid: I thought we are going away from HOBs?

**Comment by gguo11837463** [comment]
> 1. Do you expect BL to use PeiLoadFileLoadPayload PEI module? I would like to avoid using any PEIMs in UPL if possible. What if BL itself can find, load and relocate UPL?
> 2. gUniversalPayloadBaseGuid: I thought we are going away from HOBs?

1-Answer: I expect Edk2BootLoader can use FitPayLoaderPeim.inf to load UPL and relocate UPL.
Other boot loader can use similar way to load it.

2-Answer: Currently, FDT and FIT is separate tasks from PR view point. FDT will convert into gUniversalPayloadBaseGuid for backward support after FDT code ready. On Google Doc Spec only FIT has been finalize.

**Comment by sjg20** [comment]
Also build-type needs to be discussed, but please use "build-type" (no capital T)

**Comment by gguo11837463** [comment]
> ```
>         loadables = "uefi-fv,bds-fv,network-fv";
> ```
> 
> The 'loadables' property should be a string list, not a single string, i.e.:
> 
> ```
>            loadables = "uefi-fv", "bds-fv", "network-fv";
> ```
> 
> Also, do you want to always load all three, or should you have two configurations, one for local and one for network?

In the mean time, just have one configuration to one binary,

> one binary (UniversalPayload.fit) have loadables = "uefi-fv", "bds-fv";
> one binary (UniversalPayload.fit) have loadables = "uefi-fv", "bds-fv", "network-fv";

In our internal develop, maybe will have more ingredient in the future.
For example
> one binary (UniversalPayload.fit) have loadables = "uefi-fv", "bds-fv", "network-fv", "i2cfeature-fv";
> one binary (UniversalPayload.fit) have loadables = "uefi-fv", "bds-fv", "network-fv", "ecfeature-fv";

**Pull request closed without merging**
