### PR TITLE
SecurityPkg/Tcg2Config: Cast pointer type to VOID* to avoid potential build error.

### PR DESCRIPTION
**Pull request by td36**
# Description

Cast pointer type to VOID* to avoid potential build error. If the two PCD are FixAtBuild, PcdGetPtr will return a const type pointer. Since the second parameter of BuildGuidDataHob is VOID*, build error may happen with following log: 
warning C4090: 'function': different 'const' qualifiers

## How This Was Tested

Tested by tianocore edk2 CI

### CODE REVIEW

**Comment by td36** [comment]
Hi @niruiyu @jyao1 , could you help review the PR?

**Review by niruiyu — APPROVED** [review]

**Comment by leiflindholm** [comment]
Why is the breaking-change label set?

**Comment by td36** [comment]
> Why is the breaking-change label set?

Hi Leif, the build error I mentioned happens on Intel internal platforms. So the tag is set for the PR to fix the issue

**Comment by leiflindholm** [comment]
@td36 right, but my interpretation is that breaking-change is meant to indicate the PR, not what the PR is fixing.

**Pull request merged**
