### PR TITLE
Cryptopkg mbedtls reimplement sm3

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
MbedTlsLib as it is today is problematic because it still relies on OpenSSL. OpenSSL is the reason 32-bit ARM needs a softfloat library, and moving 32-bit ARM to MbedTlsLib therefore only helps this situation if the OpensslLib dependency is removed.

The only reason for this dependency is the SM3 code, which is itself 1/3 the size of all the boilerplate code we need in order to link OpenSSL into MbedTlsLib to begin with.

~~Enable~~ Add unit tests for MbedTlsLib as well so we can test the new code. They cannot be enabled, though, as MbedTls currently fails many other unit tests in the test suite.

### CODE REVIEW

**Comment by leiflindholm** [comment]
I won't pretend to have verified spec compliance or mathematical aspects, but other than those this change looks good to me, and it would be _very_ nice to drop the openssl dependency here.

**Comment by ardbiesheuvel** [comment]
cc @os-d

**Review by os-d — APPROVED** [review]
I also didn't verify the spec compliance, but I agree with the change. I will update my PR to drop the moving of ArmSoftFloatLib.

**Comment by liyi77** [comment]
I agree with the proposal of removing OpensslLib dependency, but adding EDK2's own algorithm implementation is not a good idea for me.
How about copy openssl sm3 files to Mbedtls lib? sm3 itself does not depend on float and is relatively independent in openssl.

**Comment by ardbiesheuvel** [comment]
> I agree with the proposal of removing OpensslLib dependency, but adding EDK2's own algorithm implementation is not a good idea for me. How about copy openssl sm3 files to Mbedtls lib? sm3 itself does not depend on float and is relatively independent in openssl.

IIRC the licenses were incompatible, and copying openssl code into edk2 is not possible. Has that situation changed?

**Comment by liyi77** [comment]
> > I agree with the proposal of removing OpensslLib dependency, but adding EDK2's own algorithm implementation is not a good idea for me. How about copy openssl sm3 files to Mbedtls lib? sm3 itself does not depend on float and is relatively independent in openssl.
> 
> ~IIRC the licenses were incompatible, and copying openssl code into edk2 is not possible. Has that situation changed?~
> 
> As it turns out, OpenSSL has been relicensed to Apache 2, so incorporating the code directly is in fact possible now.
> 
> I will take the core SM3 transform from OpenSSL, but retain the reimplemented logic around it, as importing that from OpenSSL is a bit of a hassle.

Sounds good. I would like recommend keeping the original openssl sm3 structures ossl_sm3_init/update/final. This way you don't have to change CryptSm3.c, and we can better track if there are related OpenSSL changes or CVEs in the future.

CryptoPkg\Library\OpensslLib\openssl\include\crypto\md32_common.h
#define HASH_UPDATE             ossl_sm3_update
#define HASH_TRANSFORM          ossl_sm3_transform
#define HASH_FINAL              ossl_sm3_final

**Comment by mdkinney** [comment]
Can Sm3 support be added to MbedTLs upstream?  Has that been suggested?

**Comment by liyi77** [comment]
> Can Sm3 support be added to MbedTLs upstream? Has that been suggested?

https://github.com/Mbed-TLS/mbedtls/pull/4492
But no any updates from 2022.

**Comment by mdkinney** [comment]
Looks like most of the work was completed.  Branch was out of date.  Better to improve MbvedTLs than add copies of files to edk2.

**Comment by ardbiesheuvel** [comment]
I don't fundamentally disagree with any of the pushback.

It would have been nice, however, if the same level of scrutiny would have been applied on the original PR that created this tangled mess in the first place.

Perhaps it is better for now to just do something along the lines of

```diff
--- a/CryptoPkg/Library/BaseCryptLibMbedTls/BaseCryptLib.inf
+++ b/CryptoPkg/Library/BaseCryptLibMbedTls/BaseCryptLib.inf
@@ -32,7 +32,6 @@ [Sources]
   Hash/CryptSha256.c
   Hash/CryptSha512.c
   Hash/CryptParallelHashNull.c
-  Hash/CryptSm3.c
   Hmac/CryptHmac.c
   Kdf/CryptHkdf.c
   Cipher/CryptAes.c
@@ -61,6 +60,12 @@ [Sources]
   SysCall/BaseMemAllocation.c
   SysCall/TimerWrapper.c
 
+[Sources.IA32, Sources.X64]
+  Hash/CryptSm3.c
+
+[Sources.ARM, Sources.AARCH64]
+  Hash/CryptSm3Null.c
+
 [Packages]
   MdePkg/MdePkg.dec
   CryptoPkg/CryptoPkg.dec
@@ -72,11 +77,14 @@ [LibraryClasses]
   UefiRuntimeServicesTableLib
   DebugLib
   MbedTlsLib
-  OpensslLib
   PrintLib
   IntrinsicLib
   RngLib
   SynchronizationLib
+
+[LibraryClasses.IA32, LibraryClasses.X64]
+  OpensslLib
+
 [Protocols]
   gEfiMpServiceProtocolGuid
 #
```

so that only x86 builds using MbedTlsLib pull in the OpenSSL dependency. ARM will never need SM3, and AArch64 firmwares that require it will likely prefer using OpenSSL directly, given that AArch64 has special instructions for SM3 and SM4 which are substantially faster than any C implementation.

**Comment by ardbiesheuvel** [comment]
> > > I agree with the proposal of removing OpensslLib dependency, but adding EDK2's own algorithm implementation is not a good idea for me. How about copy openssl sm3 files to Mbedtls lib? sm3 itself does not depend on float and is relatively independent in openssl.
> > 
> > 
> > ~IIRC the licenses were incompatible, and copying openssl code into edk2 is not possible. Has that situation changed?~
> > As it turns out, OpenSSL has been relicensed to Apache 2, so incorporating the code directly is in fact possible now.
> > I will take the core SM3 transform from OpenSSL, but retain the reimplemented logic around it, as importing that from OpenSSL is a bit of a hassle.
> 
> Sounds good. I would like recommend keeping the original openssl sm3 structures ossl_sm3_init/update/final. This way you don't have to change CryptSm3.c, and we can better track if there are related OpenSSL changes or CVEs in the future.
> 
> CryptoPkg\Library\OpensslLib\openssl\include\crypto\md32_common.h
> #define HASH_UPDATE ossl_sm3_update
> #define HASH_TRANSFORM ossl_sm3_transform
> #define HASH_FINAL ossl_sm3_final

This is what I tried to avoid.

Reusing the Merkle-Damgard boilerplate requires defining quite a few helpers: there are APIs such as OPENSSL_CLEANSE(), memset() etc that will all need to be provided in one way or the other.

Also, the way the byte counter is implemented is rather silly (with two UINT32s and a carry implemented in software), and the endian swabbing is implemented by doing byte reads.

**Comment by ardbiesheuvel** [comment]
I have looked into the SM3 situation in MbedTLS in a bit more detail, and the PR is definitely not in a state where it can be merged straight-forwardly, as a lot of refactoring has happened in the meantime.

But what is worse, the PKCS#7 code in MbedTLS appears to have regressed: https://github.com/Mbed-TLS/mbedtls/commit/6cfc4692961ba808d801ab2ffbf6e076523ccac0 removes the `content` field from the `mbedtls_pkcs7_signed_data` struct, which is referenced explicitly by the PKCS#7 glue code in MbedTLsLib.

I don't have the bandwidth currently to dig us out of this hole, so I am going to proceed with a minimal series that simply disables SM3 support for 32-bit ARM in MbedTlsLib, in order to unblock my work on removing ArmSoftFloatLib from the project entirely.

**Pull request closed without merging**
