### PR TITLE
MdePkg: Fix a buffer overread.

### PR DESCRIPTION
**Pull request by bsdjhb**
DevPathToTextUsbWWID allocates a separate copy of the SerialNumber string to append a null terminator if the original string is not null terminated.  However, by using AllocateCopyPool, it tries to copy 'Length + 1' words from the existing string containing 'Length' characters into the target string.  Split the copy out to only copy 'Length' characters instead.

This was reported by GCC's -Wstringop-overread when compiling a copy of this routine included in a library on FreeBSD.

Signed-off-by: John Baldwin <jhb@FreeBSD.org>

### CODE REVIEW

**Comment by heatd** [comment]
Hi, could you please post this patch in the EDK2 mailing list? As described in https://github.com/tianocore/tianocore.github.io/wiki/EDK-II-Development-Process

We don't do reviews here

**Comment by jlduran** [comment]
@heatd / @lersek Would you kindly reconsider reopening this pul request now that the EDK II Development Process guidelines have changed? Thank you!

**Review by lgao4 — APPROVED** [review]

**Comment by lgao4** [comment]
This change can be merged after the stable tag 202408 is created.

**Review by mdkinney — APPROVED** [review]

**Comment by mdkinney** [comment]
@mergify rebase

**Pull request merged**
