### PR TITLE
1971 fix virtio issues v1

### PR DESCRIPTION
**Pull request by samimujawar**
# Description

The storage space for virtio-scsi and the virtio-blk request headers
being shared with the host was from the stack as the request structure
was a local function variable.

A bug in the VMM can corrupt the stack space, and such issues
can be very hard to debug.

Note: This is only an issue with a normal guest VM (non-CCA).
A CCA guest VM would perform bounce buffering for sharing the
data and therefore not have this issue.

Instead of using the stack for sharing the data with the host,
memory can be allocated from the heap pool. However, pool
allocations are not any safer in terms of pages being shared
between different allocations, and so mapping a pool allocation
for DMA may expose it to potential corruption by the VMM in
exactly the same way. The only difference is the potential
impact on program behaviour, which is much higher with the
stack.

Additionally, for guest-side corruption heap allocations can
take advantage by turning on heap guard to help find the bug.

Therefore, allocate memory for the virtio-scsi and virtio-blk request
headers from the heap before sharing with the host.

- [ ] Breaking change?
  - No
- [ ] Impacts security?
  - Improves the security as the host cannot accidentally modify the guest stack.
- [ ] Includes tests?
  - No

## How This Was Tested

Kvmtool guest firmware built and tested by launching a guest using kvmtool VMM.

## Integration Instructions

N/A

### CODE REVIEW

**Comment by kraxel** [comment]
Can you give some more context please?  I just don't see how this improves security.  The host can access all guest memory anyway.  In case of confidential guests the virtio buffers are piped through shared bounce buffers (see OvmfPkg/IoMmuDxe), the stack will *not* be shared with the host.

**Comment by samimujawar** [comment]
This is only a minor improvement for a non-CCA guest where should the host software accidentally write to the guest stack area can leading to potential issues. 

Apart from this from a design perspective (not related to security), I think sharing stack variables across software components is not good.

**Comment by kraxel** [comment]
Ok, so it's about CCA guests.  It's still not clear to me how moving the allocation from stack to heap improves security.  Can the host access memory other than the request struct itself?  For example other data on the same page?  Should that be the case:  Why this isn't a problem for heap allocations?

Some background info on how memory sharing with the host work on CCA would be useful.  Pointer to docs is fine.

**Comment by samimujawar** [comment]
This patch is not applicable for a CCA guest.

**Comment by kraxel** [comment]
Yes, memory corruption bugs are indeed hard to debug, because things tend to explode far away from the actual root cause.  I fail to see why corrupting the heap instead of the stack is any better though, especially if we are talking about the /host/ corrupting memory.  For guest-side corruption heap allocations have the advantage that turning on heap guard can help find the bug.  So, yea, a minor improvement.

**Comment by samimujawar** [comment]
@ardbiesheuvel Is it possible to provide review feedback for this pull request, please?

**Review by ardbiesheuvel — COMMENTED** [review]
If CCA is out of scope here, why is this unsafe? The stack is writable memory, and all code runs at the same exception level so there are a million ways in which the stack can get corrupted, and a broken VMM writing out of bounds is only one of them.

Does this address a particular issue you encountered?

**Comment by samimujawar** [comment]
There was no specific issue. I noticed that the guest stack was being used for sharing data between the guest and the VMM. Since stack corruption can be hard to debug, I proposed this change.
Would it be better to reword the commit message to say that ‘stack corruption can be hard to debug’ instead of using the term ‘unsafe’?

**Comment by ardbiesheuvel** [comment]
> There was no specific issue. I noticed that the guest stack was being used for sharing data between the guest and the VMM. Since stack corruption can be hard to debug, I proposed this change. Would it be better to reword the commit message to say that ‘stack corruption can be hard to debug’ instead of using the term ‘unsafe’?

Yes I think that would be better. Note that, as Gerd points out, pool allocations are not any safer in terms of pages being shared between different allocations, and so mapping a pool allocation for DMA may expose it to potential corruption by the VMM in exactly the same way. The only difference is the potential impact on program behavior, which is much higher with the stack.

As long as this is all being explained in the commit log, I am happy with these patches.

**Review by ardbiesheuvel — APPROVED** [review]

**Pull request merged**
