### PR TITLE
AmdSev: Harden SEV Kernel hashes verifier

### PR DESCRIPTION
**Pull request by fitzthum**
First of all, thank you to whoever convinced everyone to switch to GitHub. This is a huge improvement imo.

I submitted a v1 of this to the list a few weeks ago and got some feedback from @tlendacky, which I have implemented. I also had a version of this PR just for testing, but I opened a new one to make the situation more clear.

Here is the cover letter that I originally sent to the list. It is a good description of these changes.

The AmdSev package has a so-called BlobVerifier, which is meant to extend the TCB of a confidential guest (SEV or SNP) to include components provided via fw_cfg such as initrd, kernel, kernel params.

This series fixes a few implementation errors in the blob verifier. One common theme is that the verifier currently fails to halt the boot when an invalid blob is detected. This can lead to a confidential guest having a launch measurement that does not reflect the guest TCB.

This series could also help us move towards consolidating the AmdSev package back into the OvmfPkg although more discussion will be needed on this.

Thank you for @ryansavino for pointing out some of these issues.

## Testing

I have tested most of these error cases locally, including with a modified version of QEMU that manipulates the kernel hashes.

### CODE REVIEW

**Review by tlendacky — APPROVED** [review]

**Comment by fitzthum** [comment]
cc: @dubek @kraxel @ardbiesheuvel

**Review by kraxel — APPROVED** [review]

**Review by dubek — APPROVED** [review]

**Comment by mdkinney** [comment]
@Mergifyio refresh

**Comment by mdkinney** [comment]
@Mergifyio rebase

**Comment by mdkinney** [comment]
Close and reopen PR to force Azure Pipelines checks to be triggered again.

**Pull request merged**
