### PR TITLE
CI: Use new Fedora-40 image for Linux jobs

### PR DESCRIPTION
**Pull request by osteffenrh**
Switch the Linux CI jobs over to the latest Fedora 40 image.

### CODE REVIEW

**Comment by osteffenrh** [comment]
There is a problem with lcov version 2.0 (and newer). This PR contains a potential fix.

See https://dev.azure.com/tianocore/edk2-ci/_build/results?buildId=152451&view=logs&jobId=7cd61938-4509-589a-75ed-329528680800 for the original error.

```
...
INFO - Processing /__w/1/s/Build/SecurityPkg/HostTest/NOOPT_GCC5/X64/SecurityPkg/Library/SecureBootVariableLib/UnitTest/SecureBootVariableLibUnitTest/OUTPUT/AutoGen.gcda
INFO - Processing /__w/1/s/Build/SecurityPkg/HostTest/NOOPT_GCC5/X64/SecurityPkg/Library/SecureBootVariableLib/GoogleTest/SecureBootVariableLibGoogleTest/OUTPUT/SecureBootVariableLibGoogleTest.gcda
INFO - geninfo: WARNING: /usr/include/c++/14/ext/atomicity.h:52: unexecuted block on non-branch line with non-zero hit count.  Use "geninfo --rc geninfo_unexecuted_blocks=1 to set count to zero.
INFO - 	(use "geninfo --ignore-errors gcov,gcov ..." to suppress this warning)
INFO - geninfo: ERROR: mismatched end line for _ZNK20SetArgBufferActionP2ILm4EPhmE10gmock_Impl17gmock_PerformImplIFvPtP4GUIDPjPyPvEvSt5tupleIJS4_S6_S7_S8_S9_EES4_S6_S7_S8_S9_N7testing8internal12ExcessiveArgESF_SF_SF_SF_EET0_RKT1_RKT2_RKT3_RKT4_RKT5_RKT6_RKT7_RKT8_RKT9_RKT10_RKT11_ at /__w/1/s/UnitTestFrameworkPkg/Include/Library/GoogleTestLib.h:47: 47 -> 55
INFO - 	(use "geninfo --ignore-errors mismatch ..." to bypass this error)
INFO - ------------------------------------------------
INFO - --------------Cmd Output Finished---------------
INFO - --------- Running Time (mm:ss): 00:01 ----------
INFO - ----------- Return Code: 0x00000001 ------------
INFO - ------------------------------------------------
```

This is a known problem. lcov 2.0 does more checks than previous versions and thus finds some
new things. This can be silenced with a command line switch.

**Comment by osteffenrh** [comment]
(Fixed copy-paste error in the image URL)

**Review by gguo11837463 — APPROVED** [review]

**Comment by osteffenrh** [comment]
@spbrogan @YuweiChen1110 @lgao4 @BobCF @bcran ping?

**Comment by osteffenrh** [comment]
Hm, that error is new after rebasing...

**Comment by osteffenrh** [comment]
> Could you resolve CI failure first?

@lgao4, fixed the CI.

This image now includes libasan and libubsan, as requested by @mdkinney here https://github.com/tianocore/containers/pull/103

**Comment by osteffenrh** [comment]
@kraxel ^

**Review by mdkinney — APPROVED** [review]

**Review by Javagedes — APPROVED** [review]

**Review by bexcran — APPROVED** [review]

**Review by kraxel — APPROVED** [review]

**Comment by mdkinney** [comment]
The change to BaseTools works with the Fedora 40 container, but breaks local builds with lcov 1.x installed.  It would be better if this change to BaseTools could detect the lcov version and add the extra flag only of lcov is 2.x.

**Comment by osteffenrh** [comment]
> @osteffenrh
> 
> The change to BaseTools works with the Fedora 40 container, but breaks local builds with lcov 1.x installed. It would be better if this change to BaseTools could detect the lcov version and add the extra flag only of lcov is 2.x.

Sorry about that - I'll add a version check.

**Comment by osteffenrh** [comment]
> > @osteffenrh
> > The change to BaseTools works with the Fedora 40 container, but breaks local builds with lcov 1.x installed. It would be better if this change to BaseTools could detect the lcov version and add the extra flag only of lcov is 2.x.
> 
> Sorry about that - I'll add a version check.

https://github.com/tianocore/edk2/pull/6507

**Pull request merged**
