### PR TITLE
Armvirt drop softfloat

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
Stop using floating point code on 32-bit ARM so the dependency on the Berkeley softfloat library can be dropped altogether.

### CODE REVIEW

**Review by kraxel — APPROVED** [review]

**Comment by mdkinney** [comment]
In the build logs I see some missing APIs when building `janson` in the `RedfishPkg`

```
INFO - /__w/1/s/RedfishPkg/Library/JsonLib/jansson/src/value.c:876: undefined reference to `__aeabi_dcmpeq'
INFO - /usr/bin/arm-linux-gnu-ld: /__w/1/s/RedfishPkg/Library/JsonLib/jansson/src/value.c:37: undefined reference to `__aeabi_dsub'
INFO - /usr/bin/arm-linux-gnu-ld: /tmp/cc35eIjE.ltrans0.ltrans.o:/__w/1/s/RedfishPkg/Library/JsonLib/jansson/src/value.c:37: undefined reference to `__aeabi_dcmpeq'
INFO - /usr/bin/arm-linux-gnu-ld: /tmp/cc35eIjE.ltrans0.ltrans.o: in function `lex_scan.constprop.0.isra.0':
INFO - /__w/1/s/RedfishPkg/PrivateLibrary/RedfishCrtLib/RedfishCrtLib.c:575: undefined reference to `__aeabi_ui2d'
INFO - /usr/bin/arm-linux-gnu-ld: /tmp/cc35eIjE.ltrans0.ltrans.o: in function `lex_scan.constprop.0.isra.0':
INFO - /__w/1/s/RedfishPkg/Library/JsonLib/load.c:722: undefined reference to `__aeabi_d2lz'
INFO - collect2: error: ld returned 1 exit status
```

**Comment by ardbiesheuvel** [comment]
> In the build logs I see some missing APIs when building `janson` in the `RedfishPkg`
> 
> ```
> INFO - /__w/1/s/RedfishPkg/Library/JsonLib/jansson/src/value.c:876: undefined reference to `__aeabi_dcmpeq'
> INFO - /usr/bin/arm-linux-gnu-ld: /__w/1/s/RedfishPkg/Library/JsonLib/jansson/src/value.c:37: undefined reference to `__aeabi_dsub'
> INFO - /usr/bin/arm-linux-gnu-ld: /tmp/cc35eIjE.ltrans0.ltrans.o:/__w/1/s/RedfishPkg/Library/JsonLib/jansson/src/value.c:37: undefined reference to `__aeabi_dcmpeq'
> INFO - /usr/bin/arm-linux-gnu-ld: /tmp/cc35eIjE.ltrans0.ltrans.o: in function `lex_scan.constprop.0.isra.0':
> INFO - /__w/1/s/RedfishPkg/PrivateLibrary/RedfishCrtLib/RedfishCrtLib.c:575: undefined reference to `__aeabi_ui2d'
> INFO - /usr/bin/arm-linux-gnu-ld: /tmp/cc35eIjE.ltrans0.ltrans.o: in function `lex_scan.constprop.0.isra.0':
> INFO - /__w/1/s/RedfishPkg/Library/JsonLib/load.c:722: undefined reference to `__aeabi_d2lz'
> INFO - collect2: error: ld returned 1 exit status
> ```

Thanks. Two questions:
1) where did you find that?
2) can we stop building RedfishPkg for ARM?

**Comment by mdkinney** [comment]
Unfortunately that level of detail is not in the web browser view.  The artifact with the `CI_BUILDLOG.txt` files needs to be downloaded.  Here is one way to navigating to the correct artifact to download:

1) Select `Details` link of failed check
2) Select `2 errors/ 1 warnings` link
3) Scroll down and select the failed job link (e.g. `Build_GCC5 TARGET_NETWORK`)
4) Select the `1 artifact` produced link
5) Expand the build job name that failed. (e.g. `Build logs TARGET_NETWORK`)
6) Select `CI_BUILDLOG.txt`.  The file will be downloaded and can be viewed with a local viewer/editor.

**Comment by mdkinney** [comment]
Removing ARM support from `RedfishPkg` can be done by removing `ARM` from the `SUPPORTED_ARCHITECTURES` define in `RedfishPkg.dsc`

https://github.com/tianocore/edk2/blob/7eff71fe690a0f5bc0be67b5b83f263d7892f9b6/RedfishPkg/RedfishPkg.dsc#L19

**Pull request merged**
