### PR TITLE
Pull bhyve assorted

### PR DESCRIPTION
**Pull request by ardbiesheuvel**

### CODE REVIEW

**Comment by medhefgo** [comment]
@ardbiesheuvel Commit ea88df6b26e93bfe12cea6804631d84e871be77c breaks ia32 secure boot:

```
$ qemu-system-x86_64 -blockdev node-name=code,driver=file,read-only=on,filename=OVMF_CODE.secboot.fd -blockdev node-name=vars,driver=file,filename=OVMF_VARS.fd -machine q35,smm=on,pflash0=code,pflash1=vars -serial stdio
!!!! IA32 Exception Type - 0E(#PF - Page-Fault)  CPU Apic ID - 00000000 !!!!
ExceptionData - 00000008  I:0 R:1 U:0 W:0 P:0 PK:0 SS:0 SGX:0
EIP  - 07FF97A6, CS  - 00000008, EFLAGS - 00000046
EAX  - 07FF2400, ECX - 07FC5140, EDX - 06AD7120, EBX - FFFFFFFF
ESP  - 07FCCDB4, EBP - 07FCCF4C, ESI - 00000000, EDI - 00000000
DS   - 00000020, ES  - 00000020, FS  - 00000020, GS  - 00000020, SS - 00000020
CR0  - 8001003B, CR2 - 06AD713C, CR3 - 07FA5000, CR4 - 00000668
DR0  - 00000000, DR1 - 00000000, DR2 - 00000000, DR3 - 00000000
DR6  - FFFF0FF0, DR7 - 00000400
GDTR - 07FC3000 0000004F, IDTR - 07FC6000 000000FF
LDTR - 00000000, TR - 00000040
FXSAVE_STATE - 07FC7D60
qemu: terminating on signal 2
```

**Comment by ardbiesheuvel** [comment]
@kraxel

**Comment by medhefgo** [comment]
> @medhefgo is this a build that targets IA32 specifically? Or is it just crashing early while still running in the IA32 part of the IA32/X64 combined OVMF build?

I believe it's the ia32 specific target as it's built from [OvmfPkgIa32.dsc](https://gitlab.archlinux.org/archlinux/packaging/packages/edk2/-/blob/main/PKGBUILD#L213).

**Comment by ardbiesheuvel** [comment]
@td36

I can reproduce this issue too, but my bisect points to 2d212083d048ee8c0f5b4b7c61720f16165427cb

```
commit 2d212083d048ee8c0f5b4b7c61720f16165427cb
Author: Dun Tan <dun.tan@intel.com>
Date:   Wed Jun 7 15:46:58 2023 +0800

    UefiCpuPkg: Use CpuPageTableLib to convert SMM paging attribute.
```


The below appears to fix it but someone else should confirm if this is the right fix.

```diff
diff --git a/UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c b/UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c
index b11264ce4aa7..0e16a9529850 100644
--- a/UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c
+++ b/UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c
@@ -31,7 +31,7 @@ SmmInitPageTable (
   InitializeSpinLock (mPFLock);
 
   mPhysicalAddressBits = 32;
-  mPagingMode          = PagingPae;
+  mPagingMode          = Paging32bit;
 
   if (FeaturePcdGet (PcdCpuSmmProfileEnable) ||
       HEAP_GUARD_NONSTOP_MODE ||

```

**Comment by medhefgo** [comment]
> I can reproduce this issue too, but my bisect points to [2d21208](https://github.com/tianocore/edk2/commit/2d212083d048ee8c0f5b4b7c61720f16165427cb)

Huh. I double checked and you're right.

But I am not sure the fix is correct. With `PagingPae` master+release crashes and master+debug works. With `Paging32bit` master+release works but master+debug freezes/shows a black screen instead.

**Pull request merged**
