### PR TITLE
MdeModulePkg/RamDiskDxe: fix memory leak.

### PR DESCRIPTION
**Pull request by ghbaccount**
# Description

I found this memory leak during code review.
This a common type of a leak on error path.

## How This Was Tested

No tests. A trivial memory leak issue.

## Integration Instructions

N/A

### CODE REVIEW

**Comment by leiflindholm** [comment]
Thanks for this. I'm not the maintainer of this module, but the code change looks good to me.
However, can you improve the commit message a bit? I've seen you do that better elsewhere :)

**Review by lgao4 — APPROVED** [review]

**Comment by ghbaccount** [comment]
> Thanks for this. I'm not the maintainer of this module, but the code change looks good to me.
> However, can you improve the commit message a bit? I've seen you do that better elsewhere :)

I've changed the commit message, now it's clear about leak error path and possible size of a this leak :)
Thanks!

**Comment by ghbaccount** [comment]
A gentle ping.

**Comment by mdkinney** [comment]
@lgao4 This PR was approved back in June but has not been merged. Is there any additonal feedback?

**Comment by lgao4** [comment]
> @lgao4 This PR was approved back in June but has not been merged. Is there any additional feedback?

I have no other feedback. Seemly, I miss this one. I will merge it.

**Pull request merged**
